### ISSUE TITLE
Should we delete this repo?

### ISSUE THREAD

**Issue by ethan92429** [AguaClara/aide#11]
@oliver-leung Since we've made the aguaclara repo that holds all the design files, is it necessary to have this repo?

**Comment by oliver-leung** [comment]
I think we should keep this repo so that AIDE has a home in which we can put reports and whatnot.

**Comment by ethan92429** [comment]
OK, fine by me! It is possible that AIDE could use the aguaclara repo docs to show progress. Like when a new function is written, that shows up in the docs. Or if they want to outline a design process, like "we start by calculating the plan view area of the flocculator, then..." Is there an example of when the docs wouldn't substitute for a report?

**Comment by fletchapin** [comment]
I think detailing the thought process behind designs and what one-time steps might’ve been done in a report could be useful because information like that isn’t usually in the docs.

The past month or so I’ve had to go through a lot of orientation which involved one-time actions if the previous person would’ve documented it that would’ve been super helpful. Also while going through the code base I often wonder why they did something a certain way instead of another way which appears easier and having an explanation of that thought process could save future team members from pursuing a dead end. 

Not sure if this is helpful, but just my 2 cents.
