### ISSUE TITLE
Summer Research Report - 2nd Draft

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara/aide#9]
We've finished our 2nd draft of our Summer Research Report: it can be found [here](https://github.com/AguaClara/aide/blob/master/reports/AIDE_Summer2018report_Draft2.md) or in our `reports` folder.

**Comment by IanCullings** [comment]
Hey guys, great job on the report.  I've pushed some small changes, the comments are in bold.

Following our discussion on Thursday about team structure, please update this report to include the fate of each subteam for the next semester.  This should include whether the team will continue next semester, the structure of that team, and a rough outline of the challenges the team will be working on.

Additionally, once we have reached a decision about Onshape (assuming we haven't already) please update the documentation and the report to reflect that we will be using Onshape.  For teams like GUI that interface with Fusion directly, please write a little bit about how that transition will be made.

Finally, complete the following steps to submit your final report:

- [ ] Update the report with any progress since last updating it
- [ ] Rename your report AIDE_Summer2018_final and push all changes
- [ ] Update the README to include links to both this document and your final presentation. Make sure to add information so people know what is in the report and why it would be helpful for them
- [ ] Update the [Challenges document](https://docs.google.com/document/d/17IABdAHekIp7-Y1m9bur86EgGqYvO9fMfic8clNR7nQ/edit#) with the new team structure (once we have discussed this on Thursday)
- [ ] Close any remaining Github issues you've written that are not relevant for the Fall Subteam
